/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examennetbeans;

import java.util.Random;
/**
 *
 * @author senpai
 */
public class Juego extends javax.swing.JFrame {
 Random random = new Random();
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_ataque_jugador1 = new javax.swing.JButton();
        btn_ataque_jugador2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_vida_jugador1 = new javax.swing.JLabel();
        lbl_vida_jugador2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_turno = new javax.swing.JLabel();
        lbl_game_over = new javax.swing.JLabel();
        bar_jugador1 = new javax.swing.JProgressBar();
        bar_jugador2 = new javax.swing.JProgressBar();
        btn_ataque_jugador2_2 = new javax.swing.JButton();
        btn_ataque_jugador1_1 = new javax.swing.JButton();
        btn_ataque_jugador2_3 = new javax.swing.JButton();
        btn_ataque_jugador1_3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PieceValkiriabltG.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btn_ataque_jugador1.setText("Cast Spell");
        btn_ataque_jugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ataque_jugador1MousePressed(evt);
            }
        });

        btn_ataque_jugador2.setText("Attack");
        btn_ataque_jugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ataque_jugador2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PieceBansheebltG.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setText("Vida:");

        jLabel4.setText("Vida:");

        lbl_vida_jugador1.setText("100");

        lbl_vida_jugador2.setText("100");

        jLabel5.setText("Turno");

        lbl_turno.setText("Jugador 1");

        bar_jugador1.setValue(100);

        bar_jugador2.setValue(100);

        btn_ataque_jugador2_2.setText("whirlwind");
        btn_ataque_jugador2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ataque_jugador2_2MousePressed(evt);
            }
        });

        btn_ataque_jugador1_1.setText("Fire ball");
        btn_ataque_jugador1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ataque_jugador1_1MousePressed(evt);
            }
        });

        btn_ataque_jugador2_3.setText("Victory Shout");
        btn_ataque_jugador2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ataque_jugador2_3MousePressed(evt);
            }
        });

        btn_ataque_jugador1_3.setText("Swarn of shadows");
        btn_ataque_jugador1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ataque_jugador1_3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_ataque_jugador2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bar_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_vida_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_ataque_jugador1_3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_ataque_jugador1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_ataque_jugador1_1)))
                                        .addGap(181, 181, 181)))
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_vida_jugador2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bar_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ataque_jugador2_2))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(285, 285, 285)
                                        .addComponent(lbl_turno)
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(30, 30, 30)))
                                .addComponent(lbl_game_over, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(585, 585, 585)
                                .addComponent(btn_ataque_jugador2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_game_over, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_turno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bar_jugador1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ataque_jugador1)
                        .addComponent(lbl_vida_jugador1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ataque_jugador1_1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ataque_jugador1_3)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bar_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_vida_jugador2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ataque_jugador2)
                    .addComponent(btn_ataque_jugador2_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ataque_jugador2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ataque_jugador1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque_jugador1MousePressed
       if (lbl_turno.getText().equals("Jugador 1"))
       {
        int vida_jugador2 = Integer.parseInt(lbl_vida_jugador2.getText());
        vida_jugador2-= random.nextInt(10);
        
       if(vida_jugador2<=0)
       {
          vida_jugador2 = 0;
          lbl_game_over.setText("Juego terminado, el jugador 1 ha ganado!"); 
          btn_ataque_jugador1.setEnabled(false);
          btn_ataque_jugador2.setEnabled(false);
          btn_ataque_jugador1_1.setEnabled(false);
       }else
       {
           lbl_turno.setText("Jugador 2");
           btn_ataque_jugador1.setEnabled(false);
           btn_ataque_jugador2.setEnabled(true);
           btn_ataque_jugador1_1.setEnabled(false);
       }
       //bar_jugador1
       lbl_vida_jugador2.setText("" + vida_jugador2);
               
       
       }
    }//GEN-LAST:event_btn_ataque_jugador1MousePressed

    private void btn_ataque_jugador2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque_jugador2MousePressed
         if (lbl_turno.getText().equals("Jugador 2"))
       {
        int vida_jugador1 = Integer.parseInt(lbl_vida_jugador1.getText());
        vida_jugador1-= random.nextInt(10);
        
       if(vida_jugador1<=0)
       {
          vida_jugador1 = 0;
          lbl_game_over.setText("Juego terminado, el jugador 2 ha ganado!"); 
          btn_ataque_jugador2.setEnabled(false);
          btn_ataque_jugador1.setEnabled(false);
          btn_ataque_jugador2_2.setEnabled(false);
       }else
       {
           lbl_turno.setText("Jugador 1");
           btn_ataque_jugador2.setEnabled(false);
           btn_ataque_jugador1.setEnabled(true);
           btn_ataque_jugador2_2.setEnabled(false);
       }
        lbl_vida_jugador1.setText("" + vida_jugador1);
               
       
       }
                                                    

    }//GEN-LAST:event_btn_ataque_jugador2MousePressed

    private void btn_ataque_jugador2_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque_jugador2_2MousePressed
        if (lbl_turno.getText().equals("Jugador 2"))
       {
        int vida_jugador1 = Integer.parseInt(lbl_vida_jugador1.getText());
        vida_jugador1 -= random.nextInt(20);
        
       if(vida_jugador1<=0)
       {
          vida_jugador1 = 0;
          lbl_game_over.setText("Juego terminado, el jugador 2 ha ganado!"); 
          btn_ataque_jugador2.setEnabled(false);
          btn_ataque_jugador1.setEnabled(false);
          btn_ataque_jugador2_2.setEnabled(false);
       }else
       {
           lbl_turno.setText("Jugador 1");
           btn_ataque_jugador2.setEnabled(false);
           btn_ataque_jugador1.setEnabled(true);
           btn_ataque_jugador2_2.setEnabled(false);
       }
        lbl_vida_jugador1.setText("" + vida_jugador1);
               
       
       }
    }//GEN-LAST:event_btn_ataque_jugador2_2MousePressed

    private void btn_ataque_jugador1_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque_jugador1_1MousePressed
         if (lbl_turno.getText().equals("Jugador 1"))
       {
        int vida_jugador2 = Integer.parseInt(lbl_vida_jugador2.getText());
        vida_jugador2 -= random.nextInt(20);
        
       if(vida_jugador2<=0)
       {
          vida_jugador2 = 0;
          lbl_game_over.setText("Juego terminado, el jugador 1 ha ganado!"); 
          btn_ataque_jugador1.setEnabled(false);
          btn_ataque_jugador2.setEnabled(false);
       }else
       {
           lbl_turno.setText("Jugador 2");
           btn_ataque_jugador1.setEnabled(false);
           btn_ataque_jugador2.setEnabled(true);
       }
       //bar_jugador1
       lbl_vida_jugador2.setText("" + vida_jugador2);
               
       
       }
    }//GEN-LAST:event_btn_ataque_jugador1_1MousePressed

    private void btn_ataque_jugador2_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque_jugador2_3MousePressed
      if (lbl_turno.getText().equals("Jugador 2"))
       {
        int vida_jugador1 = Integer.parseInt(lbl_vida_jugador1.getText());
        vida_jugador1-= random.nextInt(50);
        
       if(vida_jugador1<=0)
       {
          vida_jugador1 = 0;
          lbl_game_over.setText("Juego terminado, el jugador 2 ha ganado!"); 
          btn_ataque_jugador2.setEnabled(false);
          btn_ataque_jugador1.setEnabled(false);
          btn_ataque_jugador2_2.setEnabled(false);
       }else
       {
           lbl_turno.setText("Jugador 1");
           btn_ataque_jugador2.setEnabled(false);
           btn_ataque_jugador1.setEnabled(true);
           btn_ataque_jugador2_2.setEnabled(false);
       }
        lbl_vida_jugador1.setText("" + vida_jugador1);
               
       
       }
                
    }//GEN-LAST:event_btn_ataque_jugador2_3MousePressed

    private void btn_ataque_jugador1_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque_jugador1_3MousePressed
        if (lbl_turno.getText().equals("Jugador 1"))
       {
        int vida_jugador2 = Integer.parseInt(lbl_vida_jugador2.getText());
        vida_jugador2 -= random.nextInt(50);
        
       if(vida_jugador2<=0)
       {
          vida_jugador2 = 0;
          lbl_game_over.setText("Juego terminado, el jugador 1 ha ganado!"); 
          btn_ataque_jugador1.setEnabled(false);
          btn_ataque_jugador2.setEnabled(false);
       }else
       {
           lbl_turno.setText("Jugador 2");
           btn_ataque_jugador1.setEnabled(false);
           btn_ataque_jugador2.setEnabled(true);
       }
       //bar_jugador1
       lbl_vida_jugador2.setText("" + vida_jugador2);
               
       
       }
    }//GEN-LAST:event_btn_ataque_jugador1_3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar_jugador1;
    private javax.swing.JProgressBar bar_jugador2;
    private javax.swing.JButton btn_ataque_jugador1;
    private javax.swing.JButton btn_ataque_jugador1_1;
    private javax.swing.JButton btn_ataque_jugador1_3;
    private javax.swing.JButton btn_ataque_jugador2;
    private javax.swing.JButton btn_ataque_jugador2_2;
    private javax.swing.JButton btn_ataque_jugador2_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_game_over;
    private javax.swing.JLabel lbl_turno;
    private javax.swing.JLabel lbl_vida_jugador1;
    private javax.swing.JLabel lbl_vida_jugador2;
    // End of variables declaration//GEN-END:variables
}
